### ISSUE TITLE
Max point size

### ISSUE THREAD

**Issue by archasek** [Semafind/semadb#14]
Hey, got an error: `point 0 exceeds maximum point size 13085 > 4096`. In docs I can see it's mentioned `Maximum vector size / dimensions is 4096`. I use 512 dimensions per indexed property (I have 5), so I was thinking that's fine? Apparently there's another limit not covered by docs?

**Comment by nuric** [comment]
Hi 👋

You can adjust the maximum point size in the [configuration](https://semadb.com/docs/configuration/) by changing field in the user plan section. The point size is the whole encoded point in bytes (including vector) by [message pack](https://msgpack.org/index.html). You can change it to a higher value for sure, it is just there to stop accidental inserts of really large points that could strain the database or allow different user plans.

The maximum vector size (dimensions) is set to 4096 which is separate from the point size, you can have a lot of metadata for small vector points.

💭 Where in the docs does it mention that? I can update it so it's clear.

**Comment by archasek** [comment]
Thanks @nuric. I'm using SemaDB via REST API at the moment - isn't the config for on premise usage only?

**Comment by nuric** [comment]
Ah yes, that's correct. The configuration is for self-hosting. The cloud hosted version does have point size restrictions to avoid large vector dumps and I think the basic free version is indeed 4096 bytes shown on the [pricing page](https://rapidapi.com/semafind-semadb/api/semadb/pricing).

How about, send an email to contact@semafind.com with your use case and maybe we can give larger trial subscription. We do have an education licence for example. I'll pick up the support / contact ticket.
