### ISSUE TITLE
runner

### ISSUE THREAD

**Issue by gedw99** [Semafind/semadb#9]
https://github.com/cirello-io/runner can run many thing with cross dependencies.

it will make it easier to run all the parts of semi rom one config.

**Comment by nuric** [comment]
Could be useful for development, especially for the cluster run version. But would require installation of runner rather than running a pre-made bash script. Could add a procfile to the issue for people who want to use it.

**Comment by gedw99** [comment]
I would like it, but am currently working on other stuff so will have to let someone else do this.

The ProcFile is pretty easy and because you know the services to run its more efficient for you to do I think.
